// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WCP.Repositories.Models;

[Table("WatercolorsPainting")]
public partial class WatercolorsPainting
{
    [Key]
    [StringLength(45)]
    public string PaintingId { get; set; }

    [Required]
    [StringLength(100)]
    [RegularExpression("^(?:[A-Z][a-z0-9]*(?:\\s[A-Z][a-z0-9]*)*)$", ErrorMessage = "Each word must begin with a capital letter and contain only letters, spaces, and digits.")]
    public string PaintingName { get; set; }

    [Required]
    [StringLength(250)]
    public string PaintingDescription { get; set; }

    [Required]
    [StringLength(120)]
    public string PaintingAuthor { get; set; }

    [Required]
    [Column(TypeName = "decimal(18, 0)")]
    [Range(0, (double)decimal.MaxValue, ErrorMessage = "Price must be greater than or equal to 0.")]
    public decimal? Price { get; set; }

    [Required]
    [Range(1000, int.MaxValue, ErrorMessage = "Publish Year must be greater than or equal to 1000.")]
    public int? PublishYear { get; set; }

    [Required]
    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Required]
    [StringLength(30)]
    public string StyleId { get; set; }

    [ForeignKey("StyleId")]
    [InverseProperty("WatercolorsPaintings")]
    public virtual Style Style { get; set; }
}