// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using BusinessObject.Shared.Models.Blogs;
using Microsoft.EntityFrameworkCore;

namespace BusinessObject.Shared.Models.BlogImages;

public partial class BlogImage
{
    [Key]
    [Column("ID")]
    public Guid Id { get; set; }

    [Column("BlogID")]
    public Guid BlogId { get; set; }

    [Required]
    [StringLength(255)]
    public string ImageUrl { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [StringLength(255)]
    public string Caption { get; set; }

    [StringLength(255)]
    public string AltText { get; set; }

    public bool IsPrimary { get; set; }

    public int? ImageSize { get; set; }

    [StringLength(50)]
    public string UploadedByName { get; set; }

    [ForeignKey("BlogId")]
    [InverseProperty("BlogImages")]
    public virtual Blog Blog { get; set; }
}