// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PE.Repository.Models;

[PrimaryKey("EmployeeId", "SkillId")]
[Table("Employee_Skills")]
public partial class EmployeeSkill
{
    [Key]
    [Column("EmployeeID")]
    public int EmployeeId { get; set; }

    [Key]
    [Column("SkillID")]
    public int SkillId { get; set; }

    [StringLength(255)]
    public string ProficiencyLevel { get; set; }

    public DateOnly? AcquiredDate { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("EmployeeSkills")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("SkillId")]
    [InverseProperty("EmployeeSkills")]
    public virtual Skill Skill { get; set; }
}