// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PE.Repository.Models;

[PrimaryKey("EmployeeId", "ProjectId")]
[Table("Employee_Projects")]
public partial class EmployeeProject
{
    [Key]
    [Column("EmployeeID")]
    public int EmployeeId { get; set; }

    [Key]
    [Column("ProjectID")]
    public int ProjectId { get; set; }

    [StringLength(255)]
    public string Role { get; set; }

    public DateOnly? JoinDate { get; set; }

    public DateOnly? LeaveDate { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("EmployeeProjects")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("EmployeeProjects")]
    public virtual Project Project { get; set; }
}