// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PE.Repository.Models;

public partial class Skill
{
    [Key]
    [Column("SkillID")]
    public int SkillId { get; set; }

    [Required]
    [StringLength(255)]
    public string SkillName { get; set; }

    public string Description { get; set; }

    [InverseProperty("Skill")]
    public virtual ICollection<EmployeeSkill> EmployeeSkills { get; set; } = new List<EmployeeSkill>();
}